export const articles = [
  {
    id: 1,
    title:
      'Understanding color theory: the color wheel and finding complementary colors',
    description:
      'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum.',
    tag: 'UI DESIGN',
    imgArticleSrc: '/images/image-hero.png',
    imgArticleAlt: 'ImageHero',
    imgPeopleSrc: '/peoples/people-hero.png',
    imgPeopleAlt: 'PeopleHero',
    writter: 'Leslie Alexander',
    writterJob: 'UI Designer',
    publisedAt: 'Jul 2, 2021',
  },
  {
    id: 2,
    title: 'How to design a product that can grow itself 10x in year',
    description:
      'Auctor Porta. Augue vitae diam mauris faucibus blandit elit per, feugiat leo dui orci. Etiam vestibulum. Nostra netus per conubia dolor.',
    tag: 'INTERNET',
    imgArticleSrc: '/images/image-1.png',
    imgArticleAlt: 'Image1',
    imgPeopleSrc: '/peoples/people-hero.png',
    imgPeopleAlt: 'People1',
    writter: 'Jenny Wilson',
    writterJob: 'Product Manager',
    publisedAt: 'June 28, 2021',
  },
  {
    id: 3,
    title: 'The More Important the Work, the More Important the Rest',
    description:
      'Suitable Quality is determined by product users, clients or customers, not by society in general. For example, a low priced product may be viewed as having high.',
    tag: '9 TO 5',
    imgArticleSrc: '/images/image-2.png',
    imgArticleAlt: 'Image2',
    imgPeopleSrc: '/peoples/people-hero.png',
    imgPeopleAlt: 'People2',
    writter: 'Esther Howard',
    writterJob: 'Enterpreneur',
    publisedAt: 'June 22, 2021',
  },
  {
    id: 4,
    title: 'Email Love - Email Inspiration, Templates and Discovery',
    description:
      'Consider that for a moment: everything we see around us is assumed to have had a cause and is contingent upon something else.',
    tag: 'INSPIRATIONS',
    imgArticleSrc: '/images/image-3.png',
    imgArticleAlt: 'Image3',
    imgPeopleSrc: '/peoples/people-hero.png',
    imgPeopleAlt: 'People3',
    writter: 'Robert Fox',
    writterJob: 'Front-end Engineer',
    publisedAt: 'June 18, 2021',
  },
  {
    id: 5,
    title: 'The More Important the Work, the More Important the Rest',
    description:
      'Suitable Quality is determined by product users, clients or customers, not by society in general. For example, a low priced product may be viewed as having high.',
    tag: '9 TO 5',
    imgArticleSrc: '/images/image-4.png',
    imgArticleAlt: 'Image4',
    imgPeopleSrc: '/peoples/people-hero.png',
    imgPeopleAlt: 'People4',
    writter: 'Esther Howard',
    writterJob: 'Enterpreneur',
    publisedAt: 'June 22, 2021',
  },
  {
    id: 6,
    title: 'Email Love - Email Inspiration, Templates and Discovery',
    description:
      'Consider that for a moment: everything we see around us is assumed to have had a cause and is contingent upon something else.',
    tag: 'INSPIRATIONS',
    imgArticleSrc: '/images/image-5.png',
    imgArticleAlt: 'Image5',
    imgPeopleSrc: '/peoples/people-hero.png',
    imgPeopleAlt: 'People5',
    writter: 'Robert Fox',
    writterJob: 'Front-end Engineer',
    publisedAt: 'June 18, 2021',
  },
  {
    id: 2,
    title: 'How to design a product that can grow itself 10x in year',
    description:
      'Auctor Porta. Augue vitae diam mauris faucibus blandit elit per, feugiat leo dui orci. Etiam vestibulum. Nostra netus per conubia dolor.',
    tag: 'INTERNET',
    imgArticleSrc: '/images/image-6.png',
    imgArticleAlt: 'Image6',
    imgPeopleSrc: '/peoples/people-hero.png',
    imgPeopleAlt: 'People6',
    writter: 'Jenny Wilson',
    writterJob: 'Product Manager',
    publisedAt: 'June 28, 2021',
  },
];
